/*

 JANPU.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char janpu[] =
{
  0x1C,0x1C,0x3E,0x22,0x75,0x4B,0xFF,0x81,
  0xFF,0xA1,0xFF,0xBF,0x7F,0x65,0x3F,0x3F,
  0x1C,0x1C,0x3E,0x22,0x75,0x4B,0xEF,0x91,
  0xF1,0xAF,0xFF,0xBF,0x7F,0x65,0x3F,0x3F
};

/* End of JANPU.C */
