/*

 WORLD1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\users\crossover\Documents\programming\gbDev\games\gb\janpukid\raw\world1tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define world1mapWidth 40
#define world1mapHeight 18
#define world1mapBank 0

extern unsigned char world1map[];

/* End of WORLD1MAP.H */
